### ISSUE TITLE
Need creating pv and pvc before hand?

### ISSUE THREAD

**Issue by jianlianggao** [phnmnl/phenomenal-h2020#1]
the galaxy-k8s-rc.yaml hasn't defined pv and pvc volume. Do we need creating pv and pvc before hand?

**Comment by pcm32** [comment]
Yes, the Replication Controller (RC) doesn't include the Persistent Volume and the Persistent Volume Claim. I have a Helm based installation where we could include the PV for the sake of minikube.

**Comment by pcm32** [comment]
If you follow the helm-based installation [here](https://github.com/phnmnl/phenomenal-h2020/wiki/QuickStart-Installation-for-Local-PhenoMeNal-Workflow), it will create the PV for you inside minikube.
