### ISSUE TITLE
Documentation "Overview Cloud Research Environment"

### ISSUE THREAD

**Issue by namratakale** [phnmnl/phenomenal-h2020#21]
The documentation is about what/why to use PhenoMeNal and does not seem to go with the title.

**Comment by korseby** [comment]
@namratakale  Sorry, I'm not the right person to do this, as I only aggregated the page from existing pages someone else has created and made some corrections and additions mostly in the places I work with. At least, @DSchober @sneumann @michaelvanvliet @pcm32 @khaug @sh107 @proccaserra have also worked on these pages. Maybe they have a better overview on the whole CRE and can contribute in a better way?
