### ISSUE TITLE
Deployment Cloud Research Environment

### ISSUE THREAD

**Issue by namratakale** [phnmnl/phenomenal-h2020#22]
This is a repetition of PhenoMeNal Accessing Metabolomics Workflows in Galaxy

**Comment by korseby** [comment]
@namratakale Can you explain what you want to see in this chapter? I think, we already have explained most of the things [here](https://github.com/phnmnl/phenomenal-h2020/wiki/Deployment-Cloud-Research-Environment), [here](https://github.com/phnmnl/phenomenal-h2020/wiki/Starting-a-PhenoMeNal-CRE-on-a-public-or-private-cloud-provider) and [here](https://github.com/phnmnl/phenomenal-h2020/wiki/Starting-a-PhenoMeNal-CRE-on-a-local-server-(bare-metal)).

**Comment by namratakale** [comment]
what i meant was the text underneath is already covered under PhenoMeNal accessing.... so why are we repeating?

**Comment by korseby** [comment]
Yes, some things in [Portal](https://github.com/phnmnl/phenomenal-h2020/wiki/Deployment-Cloud-Research-Environment) do overlap with [Overview](https://github.com/phnmnl/phenomenal-h2020/wiki/Overview-Cloud-Research-Environment) and might be merged. The other two are pretty concise. But my knowledge with the Portal is limited as I am more involved with Galaxy, tools and containers.
