### ISSUE TITLE
Continuous Integration in PhenoMeNal

### ISSUE THREAD

**Issue by namratakale** [phnmnl/phenomenal-h2020#27]
the tutorial needs update. still missing information on 'How to add your software tool to Jenkins'.

**Comment by ilveroluca** [comment]
@namratakale could we get a link to the tutorial?

In the meantime, I'll summarize the comments from @pcm32 regarding this issue below:

```
How to add tools to Jenkins: https://github.com/phnmnl/phenomenal-h2020/wiki/Jenkins-Guide

That page is linked from https://github.com/phnmnl/phenomenal-h2020/wiki/How-to-make-your-software-tool-available-through-PhenoMeNal
```

Evidently the relevance of these pages is not clear from the tutorial so we'll look into improving this.

**Comment by namratakale** [comment]
@ilveroluca https://github.com/phnmnl/phenomenal-h2020/wiki/Continuous-Integration-in-PhenoMeNal

**Comment by pcm32** [comment]
This is a very old and unmaintained tutorial (the one quoted by Namrata). It talks about installing Jenkins, which is completely out of the scope for PhenoMeNal. I would suggest getting rid of that page entry and make sure that all relevant pages link to https://github.com/phnmnl/phenomenal-h2020/wiki/How-to-make-your-software-tool-available-through-PhenoMeNal which is the main article developers use.

**Comment by korseby** [comment]
I agree with Pablo, @namratakale is `https://github.com/phnmnl/phenomenal-h2020/wiki/Jenkins-Guide` appropriate to you?

**Comment by pcm32** [comment]
(or in that place holder you could simply add some redirection link to the two entries I mentioned)

**Comment by namratakale** [comment]
@korseby @ilveroluca can you get rid of the page and add the redirections suggested?

**Comment by namratakale** [comment]
updated
