### ISSUE TITLE
Deploy your workflow with Ansible

### ISSUE THREAD

**Issue by namratakale** [phnmnl/phenomenal-h2020#33]
https://github.com/phnmnl/phenomenal-h2020/wiki/Deploy-your-workflow-with-Ansible the tutorial seems incomplete?

**Comment by korseby** [comment]
I think we can remove this page. Is it linked from somewhere?

**Comment by namratakale** [comment]
I am not sure if it is linked. Can we have a re-direction link to another related document.

**Comment by namratakale** [comment]
updated
