### ISSUE TITLE
Missing Vocabulary and definitions

### ISSUE THREAD

**Issue by jbradbury** [phnmnl/phenomenal-h2020#38]
The wiki page https://github.com/phnmnl/phenomenal-h2020/wiki/Vocabulary-and-definitions-in-PhenoMeNal is missing sections on:
- EGI
- Elixir Compute Platform
- Indigo DataCloud
- Vagrant

**Comment by sneumann** [comment]
I edited the page https://github.com/phnmnl/phenomenal-h2020/wiki/Vocabulary-and-definitions-in-PhenoMeNal/_compare/2a8f0bddef1d393b30b80674ba1d879708e85b60...b5eeaf9e8b299aff3328ee62a36df05f3e79360e
adding text on the four points.

**Comment by jbradbury** [comment]
Thanks @sneumann
