### ISSUE TITLE
container-registry.phenomenal-h2020.eu/phnmnl/galaxy-k8s-runtime:latest not found

### ISSUE THREAD

**Issue by jianlianggao** [phnmnl/phenomenal-h2020#47]
Dear all,

Is the container repo shut? docker search returns empty list. Any alternative options?

Best wishes,
Jianliang

**Comment by sneumann** [comment]
Hi, we're currently experiencing an issue with the Kubernetes cluster 
serving portal+registry+jenkins etc. I don't have an estimate when that'll be fixed. 
Yours, Steffen

**Comment by jianlianggao** [comment]
Hi Steffen,

Thank you very much for your quick response. I will try planemo. It seems that planemo requires to use biocontainer for docker container. I never used before. Is there anyone you can recommend for help with that and dockerized tool?

Best wishes,
Jianliang

**Comment by sneumann** [comment]
Hi, the registry is temporarily up again, but it was not a proper fix 
and it could disappear again. Good news is I know how to fix manually. 
Yours, Steffen

**Comment by jianlianggao** [comment]
Hi Steffen,

Thank you very much. I just pulled the docker successfully. But I got errors when deployed locally using minikube and helm. Any idea what happened? Thank you very much. `Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  12m                default-scheduler  Successfully assigned default/galaxy-k8s-bcg5f to minikube
  Normal   Pulling    12m                kubelet, minikube  Pulling image "container-registry.phenomenal-h2020.eu/phnmnl/galaxy-k8s-runtime:latest"
  Normal   Pulled     84s                kubelet, minikube  Successfully pulled image "container-registry.phenomenal-h2020.eu/phnmnl/galaxy-k8s-runtime:latest"
  Warning  Failed     82s                kubelet, minikube  Error: failed to start container "galaxy-k8s": Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/media/jianliang/backup2019/galaxy_planemo/test6/container-galaxy-k8s-runtime/config/job_conf.xml\\\" to rootfs \\\"/var/lib/docker/overlay2/b3472f4483f401b475b376c7b5eb455bb2110cf1cf63cc6147216a6192babbfd/merged\\\" at \\\"/var/lib/docker/overlay2/b3472f4483f401b475b376c7b5eb455bb2110cf1cf63cc6147216a6192babbfd/merged/galaxy/config/job_conf.xml\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
  Warning  Failed     81s                kubelet, minikube  Error: failed to start container "galaxy-k8s": Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/media/jianliang/backup2019/galaxy_planemo/test6/container-galaxy-k8s-runtime/config/job_conf.xml\\\" to rootfs \\\"/var/lib/docker/overlay2/0c636ce7d15cc43c9a02619cacf29ec1e70f8c52f014e902479e877b803fa04d/merged\\\" at \\\"/var/lib/docker/overlay2/0c636ce7d15cc43c9a02619cacf29ec1e70f8c52f014e902479e877b803fa04d/merged/galaxy/config/job_conf.xml\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
  Warning  Failed     67s                kubelet, minikube  Error: failed to start container "galaxy-k8s": Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/media/jianliang/backup2019/galaxy_planemo/test6/container-galaxy-k8s-runtime/config/tool_conf.xml\\\" to rootfs \\\"/var/lib/docker/overlay2/6c4934ae671c1807345eb92938f29416a96d9adab2c433f99f7e05aa39940d4d/merged\\\" at \\\"/var/lib/docker/overlay2/6c4934ae671c1807345eb92938f29416a96d9adab2c433f99f7e05aa39940d4d/merged/galaxy/config/tool_conf.xml\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
  Normal   Created    48s (x4 over 82s)  kubelet, minikube  Created container galaxy-k8s
  Normal   Pulled     48s (x3 over 81s)  kubelet, minikube  Container image "container-registry.phenomenal-h2020.eu/phnmnl/galaxy-k8s-runtime:latest" already present on machine
  Warning  Failed     47s                kubelet, minikube  Error: failed to start container "galaxy-k8s": Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/media/jianliang/backup2019/galaxy_planemo/test6/container-galaxy-k8s-runtime/config/tool_conf.xml\\\" to rootfs \\\"/var/lib/docker/overlay2/006c139bb961e6bb36e644f9cf270b493f7d80f042908c3c4df6c1719d9a50e7/merged\\\" at \\\"/var/lib/docker/overlay2/006c139bb961e6bb36e644f9cf270b493f7d80f042908c3c4df6c1719d9a50e7/merged/galaxy/config/tool_conf.xml\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
  Warning  BackOff    12s (x5 over 53s)  kubelet, minikube  Back-off restarting failed container
`

Best wishes,
Jianliang

**Comment by sneumann** [comment]
Quick guess Are you trying to mount a directory onto a file (or vice-versa)

We saw that back in the days with conduit files, but I don't remember anymore.

Gruß Steffen


I blame Android for the brevity and typos

**Comment by jianlianggao** [comment]
Hi Steffen,

That is where confused me so much. I used container-k8s-runtime (cloned from github). I didn't change any part of mounting path or volume, and got those errors. 

Best wishes,
Jianliang

**Comment by jianlianggao** [comment]
Hi Steffen,

I was in an old branch of container-galaxy-k8s-runtime. I switched to branch release/18.08.1-dalcotidine and rerun helm install . The Galaxy instance seemed to be setup OK. But I can't access http://192.168.99.100:30700/ as I got 403 Forbidden error.

Best wishes,
jianliang
